### ISSUE TITLE
Create A Table for Unique Customers

### ISSUE THREAD

**Issue by RyanYoak** [DataByne/uraPointOfSale#30]
Create a table that has e-mail as the ID and also includes fields for name, age, gender, address, and phone number.

**Comment by kyletpugh** [comment]
This is acceptable, I imagine there could be more information that may be useful but this is sufficient for our purposes at this point (or always). I would suggest that we use a very large integer as the identifier instead of email, as having to use an email in databases to connect other entries will be tedious and require that we use much more space. We can select the customer by their email from this table and then join any other tables with the customer identifier, which is just slightly different than selecting by email but is more space efficient and should theoretically only increase complexity in a statistically insignificant amount of time.
